### ISSUE TITLE
有从 Monet 迁移的文档吗？

### ISSUE THREAD

**Issue by SkyD666** [Kyant0/m3color#1]
从 Kotlin 换到了 Java，差别还是有一些。

**Comment by Kyant0** [comment]
如果您使用的是类似于 Int.a1 的函数，您可以使用 HCT 自定义一个

**Comment by Kyant0** [comment]
这个库推荐使用 readme 里面的 Color Scheme，因为现在颜色已经足够准确。

**Comment by SkyD666** [comment]
这个库跟readme第一行的库有什么关系呢？

**Comment by Kyant0** [comment]
那个库不能单独导入，需要配合mdc使用
