### ISSUE TITLE
Kotlin?

### ISSUE THREAD

**Issue by T8RIN** [Kyant0/m3color#2]
Will it be available on kotlin? I know i can use java in kotlin, but it will be good to create kotlin version for KMP

**Comment by Kyant0** [comment]
I also hope there is a kotlin library, but Google is updating its library and I can't better maintain this library if I use kotlin.

**Comment by T8RIN** [comment]
Oh, i got it

**Comment by T8RIN** [comment]
Maybe at least your custom classes?

**Comment by jordond** [comment]
> Maybe at least your custom classes?

You can try out [Material Kolor](https://github.com/jordond/materialkolor)

**Comment by T8RIN** [comment]
Thanks

**Comment by Kyant0** [comment]
Closed as not intended
