### ISSUE TITLE
New tonal specs

### ISSUE THREAD

**Issue by T8RIN** [Kyant0/m3color#3]
https://android-review.googlesource.com/c/platform/frameworks/support/+/2865794/2/compose/material3/material3/src/androidMain/kotlin/androidx/compose/material3/DynamicTonalPalette.android.kt

Will it be implemented? I mean to support my given key color

**Comment by Kyant0** [comment]
Yes, it's already supported. Sorry for the late response.

**Comment by T8RIN** [comment]
How?

**Comment by T8RIN** [comment]
Or it's done internally?

**Comment by Kyant0** [comment]
<img width="330" alt="image" src="https://github.com/Kyant0/m3color/assets/76829190/bff5b60f-0015-43ba-b51e-24866211671e">
